// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCleanupService creates a new instance of MockCleanupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupService {
	mock := &MockCleanupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCleanupService is an autogenerated mock type for the CleanupService type
type MockCleanupService struct {
	mock.Mock
}

type MockCleanupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleanupService) EXPECT() *MockCleanupService_Expecter {
	return &MockCleanupService_Expecter{mock: &_m.Mock}
}

// ScheduleDelete provides a mock function for the type MockCleanupService
func (_mock *MockCleanupService) ScheduleDelete(ctx context.Context, userID uuid.UUID, ids []string) {
	_mock.Called(ctx, userID, ids)
	return
}

// MockCleanupService_ScheduleDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleDelete'
type MockCleanupService_ScheduleDelete_Call struct {
	*mock.Call
}

// ScheduleDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - ids []string
func (_e *MockCleanupService_Expecter) ScheduleDelete(ctx interface{}, userID interface{}, ids interface{}) *MockCleanupService_ScheduleDelete_Call {
	return &MockCleanupService_ScheduleDelete_Call{Call: _e.mock.On("ScheduleDelete", ctx, userID, ids)}
}

func (_c *MockCleanupService_ScheduleDelete_Call) Run(run func(ctx context.Context, userID uuid.UUID, ids []string)) *MockCleanupService_ScheduleDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCleanupService_ScheduleDelete_Call) Return() *MockCleanupService_ScheduleDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCleanupService_ScheduleDelete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, ids []string)) *MockCleanupService_ScheduleDelete_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockCleanupService
func (_mock *MockCleanupService) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockCleanupService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCleanupService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCleanupService_Expecter) Start(ctx interface{}) *MockCleanupService_Start_Call {
	return &MockCleanupService_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockCleanupService_Start_Call) Run(run func(ctx context.Context)) *MockCleanupService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCleanupService_Start_Call) Return() *MockCleanupService_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCleanupService_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockCleanupService_Start_Call {
	_c.Run(run)
	return _c
}
