// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortener creates a new instance of MockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortener {
	mock := &MockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortener is an autogenerated mock type for the Shortener type
type MockShortener struct {
	mock.Mock
}

type MockShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortener) EXPECT() *MockShortener_Expecter {
	return &MockShortener_Expecter{mock: &_m.Mock}
}

// Shorten provides a mock function for the type MockShortener
func (_mock *MockShortener) Shorten(url string) (string, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockShortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - url string
func (_e *MockShortener_Expecter) Shorten(url interface{}) *MockShortener_Shorten_Call {
	return &MockShortener_Shorten_Call{Call: _e.mock.On("Shorten", url)}
}

func (_c *MockShortener_Shorten_Call) Run(run func(url string)) *MockShortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortener_Shorten_Call) Return(s string, err error) *MockShortener_Shorten_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShortener_Shorten_Call) RunAndReturn(run func(url string) (string, error)) *MockShortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}
