// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/newmersedez/urlshort/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRepository
func (_mock *MockRepository) Add(ctx context.Context, shortenURL *model.ShortenURL) error {
	ret := _mock.Called(ctx, shortenURL)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ShortenURL) error); ok {
		r0 = returnFunc(ctx, shortenURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenURL *model.ShortenURL
func (_e *MockRepository_Expecter) Add(ctx interface{}, shortenURL interface{}) *MockRepository_Add_Call {
	return &MockRepository_Add_Call{Call: _e.mock.On("Add", ctx, shortenURL)}
}

func (_c *MockRepository_Add_Call) Run(run func(ctx context.Context, shortenURL *model.ShortenURL)) *MockRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ShortenURL
		if args[1] != nil {
			arg1 = args[1].(*model.ShortenURL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Add_Call) Return(err error) *MockRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Add_Call) RunAndReturn(run func(ctx context.Context, shortenURL *model.ShortenURL) error) *MockRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddBatch provides a mock function for the type MockRepository
func (_mock *MockRepository) AddBatch(ctx context.Context, shortenUrls []*model.ShortenURL) error {
	ret := _mock.Called(ctx, shortenUrls)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model.ShortenURL) error); ok {
		r0 = returnFunc(ctx, shortenUrls)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatch'
type MockRepository_AddBatch_Call struct {
	*mock.Call
}

// AddBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenUrls []*model.ShortenURL
func (_e *MockRepository_Expecter) AddBatch(ctx interface{}, shortenUrls interface{}) *MockRepository_AddBatch_Call {
	return &MockRepository_AddBatch_Call{Call: _e.mock.On("AddBatch", ctx, shortenUrls)}
}

func (_c *MockRepository_AddBatch_Call) Run(run func(ctx context.Context, shortenUrls []*model.ShortenURL)) *MockRepository_AddBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model.ShortenURL
		if args[1] != nil {
			arg1 = args[1].([]*model.ShortenURL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AddBatch_Call) Return(err error) *MockRepository_AddBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddBatch_Call) RunAndReturn(run func(ctx context.Context, shortenUrls []*model.ShortenURL) error) *MockRepository_AddBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Dispose provides a mock function for the type MockRepository
func (_mock *MockRepository) Dispose() {
	_mock.Called()
	return
}

// MockRepository_Dispose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispose'
type MockRepository_Dispose_Call struct {
	*mock.Call
}

// Dispose is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Dispose() *MockRepository_Dispose_Call {
	return &MockRepository_Dispose_Call{Call: _e.mock.On("Dispose")}
}

func (_c *MockRepository_Dispose_Call) Run(run func()) *MockRepository_Dispose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Dispose_Call) Return() *MockRepository_Dispose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Dispose_Call) RunAndReturn(run func()) *MockRepository_Dispose_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, ID string) (*model.ShortenURL, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ShortenURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortenURL, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortenURL); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortenURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockRepository_Expecter) Get(ctx interface{}, ID interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, ID string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(shortenURL *model.ShortenURL, err error) *MockRepository_Get_Call {
	_c.Call.Return(shortenURL, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ID string) (*model.ShortenURL, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepository
func (_mock *MockRepository) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Ping(ctx interface{}) *MockRepository_Ping_Call {
	return &MockRepository_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRepository_Ping_Call) Run(run func(ctx context.Context)) *MockRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Ping_Call) Return(err error) *MockRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}
