// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/newmersedez/urlshort/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditService creates a new instance of MockAuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditService {
	mock := &MockAuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditService is an autogenerated mock type for the AuditService type
type MockAuditService struct {
	mock.Mock
}

type MockAuditService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditService) EXPECT() *MockAuditService_Expecter {
	return &MockAuditService_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockAuditService
func (_mock *MockAuditService) Notify(event *model.AuditEvent) {
	_mock.Called(event)
	return
}

// MockAuditService_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockAuditService_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - event *model.AuditEvent
func (_e *MockAuditService_Expecter) Notify(event interface{}) *MockAuditService_Notify_Call {
	return &MockAuditService_Notify_Call{Call: _e.mock.On("Notify", event)}
}

func (_c *MockAuditService_Notify_Call) Run(run func(event *model.AuditEvent)) *MockAuditService_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.AuditEvent
		if args[0] != nil {
			arg0 = args[0].(*model.AuditEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditService_Notify_Call) Return() *MockAuditService_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditService_Notify_Call) RunAndReturn(run func(event *model.AuditEvent)) *MockAuditService_Notify_Call {
	_c.Run(run)
	return _c
}
