// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/newmersedez/urlshort/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRepository
func (_mock *MockRepository) Add(ctx context.Context, shortenURL *model.ShortenURL) error {
	ret := _mock.Called(ctx, shortenURL)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ShortenURL) error); ok {
		r0 = returnFunc(ctx, shortenURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenURL *model.ShortenURL
func (_e *MockRepository_Expecter) Add(ctx interface{}, shortenURL interface{}) *MockRepository_Add_Call {
	return &MockRepository_Add_Call{Call: _e.mock.On("Add", ctx, shortenURL)}
}

func (_c *MockRepository_Add_Call) Run(run func(ctx context.Context, shortenURL *model.ShortenURL)) *MockRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ShortenURL
		if args[1] != nil {
			arg1 = args[1].(*model.ShortenURL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Add_Call) Return(err error) *MockRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Add_Call) RunAndReturn(run func(ctx context.Context, shortenURL *model.ShortenURL) error) *MockRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Dispose provides a mock function for the type MockRepository
func (_mock *MockRepository) Dispose() {
	_mock.Called()
	return
}

// MockRepository_Dispose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispose'
type MockRepository_Dispose_Call struct {
	*mock.Call
}

// Dispose is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Dispose() *MockRepository_Dispose_Call {
	return &MockRepository_Dispose_Call{Call: _e.mock.On("Dispose")}
}

func (_c *MockRepository_Dispose_Call) Run(run func()) *MockRepository_Dispose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Dispose_Call) Return() *MockRepository_Dispose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Dispose_Call) RunAndReturn(run func()) *MockRepository_Dispose_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, key string) (*model.ShortenURL, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ShortenURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortenURL, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortenURL); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortenURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) Get(ctx interface{}, key interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, key string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(shortenURL *model.ShortenURL, err error) *MockRepository_Get_Call {
	_c.Call.Return(shortenURL, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (*model.ShortenURL, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShortener creates a new instance of MockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortener {
	mock := &MockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortener is an autogenerated mock type for the Shortener type
type MockShortener struct {
	mock.Mock
}

type MockShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortener) EXPECT() *MockShortener_Expecter {
	return &MockShortener_Expecter{mock: &_m.Mock}
}

// Shorten provides a mock function for the type MockShortener
func (_mock *MockShortener) Shorten(url string) (string, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockShortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - url string
func (_e *MockShortener_Expecter) Shorten(url interface{}) *MockShortener_Shorten_Call {
	return &MockShortener_Shorten_Call{Call: _e.mock.On("Shorten", url)}
}

func (_c *MockShortener_Shorten_Call) Run(run func(url string)) *MockShortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortener_Shorten_Call) Return(s string, err error) *MockShortener_Shorten_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShortener_Shorten_Call) RunAndReturn(run func(url string) (string, error)) *MockShortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}
