package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	generateComment = "generate:reset"
	outputFile      = "reset.gen.go"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	if err := run(root); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

// run walks the directory tree from root and generates reset.gen.go
// for every package that contains structs annotated with // generate:reset.
func run(root string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		base := d.Name()
		if strings.HasPrefix(base, ".") || base == "vendor" || base == "testdata" {
			return filepath.SkipDir
		}
		return processDir(path)
	})
}

// processDir parses all Go files in dir and generates reset methods
// for annotated structs. The result is written to reset.gen.go.
func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil
	}

	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.Name, "_test") {
			continue
		}

		structs := findAnnotatedStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		src, err := generateFile(pkg.Name, structs)
		if err != nil {
			return fmt.Errorf("generate %s: %w", dir, err)
		}

		outPath := filepath.Join(dir, outputFile)
		if err := os.WriteFile(outPath, src, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		fmt.Printf("generated %s\n", outPath)
	}
	return nil
}

// structInfo holds the name and fields of an annotated struct.
type structInfo struct {
	name   string
	fields []*ast.Field
}

// findAnnotatedStructs returns all structs in the package that are
// preceded by a // generate:reset comment.
func findAnnotatedStructs(pkg *ast.Package) []structInfo {
	var result []structInfo
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !hasGenerateComment(genDecl.Doc, typeSpec.Doc) {
					continue
				}
				result = append(result, structInfo{
					name:   typeSpec.Name.Name,
					fields: structType.Fields.List,
				})
			}
		}
	}
	return result
}

// hasGenerateComment reports whether any of the provided comment groups
// contains the "// generate:reset" directive.
func hasGenerateComment(groups ...*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			if c.Text == "// "+generateComment {
				return true
			}
		}
	}
	return false
}

// generateFile builds the source of reset.gen.go for the given package
// and runs it through go/format to ensure valid formatting.
func generateFile(pkgName string, structs []structInfo) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by reset generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	for _, s := range structs {
		writeResetMethod(&buf, s)
	}
	return format.Source(buf.Bytes())
}

// writeResetMethod appends a Reset() method for the given struct to buf.
func writeResetMethod(buf *bytes.Buffer, s structInfo) {
	recv := strings.ToLower(string(s.name[0]))
	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", recv, s.name)
	fmt.Fprintf(buf, "\tif %s == nil {\n\t\treturn\n\t}\n\n", recv)
	for _, field := range s.fields {
		for _, name := range field.Names {
			writeFieldReset(buf, recv, name.Name, field.Type)
		}
	}
	fmt.Fprintf(buf, "}\n\n")
}

// writeFieldReset appends the reset statement for a single struct field.
func writeFieldReset(buf *bytes.Buffer, recv, field string, typ ast.Expr) {
	switch t := typ.(type) {
	case *ast.Ident:
		if zv, ok := primitiveZero(t.Name); ok {
			fmt.Fprintf(buf, "\t%s.%s = %s\n", recv, field, zv)
		} else {
			fmt.Fprintf(buf, "\tif resetter, ok := any(&%s.%s).(interface{ Reset() }); ok {\n", recv, field)
			fmt.Fprintf(buf, "\t\tresetter.Reset()\n\t}\n")
		}
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(buf, "\t%s.%s = %s.%s[:0]\n", recv, field, recv, field)
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s.%s)\n", recv, field)
	case *ast.StarExpr:
		writePointerFieldReset(buf, recv, field, t.X)
	case *ast.SelectorExpr:
		fmt.Fprintf(buf, "\tif resetter, ok := any(&%s.%s).(interface{ Reset() }); ok {\n", recv, field)
		fmt.Fprintf(buf, "\t\tresetter.Reset()\n\t}\n")
	}
}

// writePointerFieldReset handles *T fields.
func writePointerFieldReset(buf *bytes.Buffer, recv, field string, inner ast.Expr) {
	switch it := inner.(type) {
	case *ast.Ident:
		if zv, ok := primitiveZero(it.Name); ok {
			fmt.Fprintf(buf, "\tif %s.%s != nil {\n", recv, field)
			fmt.Fprintf(buf, "\t\t*%s.%s = %s\n\t}\n", recv, field, zv)
		} else {
			fmt.Fprintf(buf, "\tif resetter, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n",
				recv, field, recv, field)
			fmt.Fprintf(buf, "\t\tresetter.Reset()\n\t}\n")
		}
	case *ast.SelectorExpr:
		fmt.Fprintf(buf, "\tif resetter, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n",
			recv, field, recv, field)
		fmt.Fprintf(buf, "\t\tresetter.Reset()\n\t}\n")
	}
}

// primitiveZero returns the zero-value literal for known primitive types.
func primitiveZero(name string) (string, bool) {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0", true
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	}
	return "", false
}
