// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetToken(userID uuid.UUID) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockTokenService_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockTokenService_Expecter) GetToken(userID interface{}) *MockTokenService_GetToken_Call {
	return &MockTokenService_GetToken_Call{Call: _e.mock.On("GetToken", userID)}
}

func (_c *MockTokenService_GetToken_Call) Run(run func(userID uuid.UUID)) *MockTokenService_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GetToken_Call) Return(s string, err error) *MockTokenService_GetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_GetToken_Call) RunAndReturn(run func(userID uuid.UUID) (string, error)) *MockTokenService_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserId provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetUserId(token string) (uuid.UUID, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserId")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GetUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserId'
type MockTokenService_GetUserId_Call struct {
	*mock.Call
}

// GetUserId is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) GetUserId(token interface{}) *MockTokenService_GetUserId_Call {
	return &MockTokenService_GetUserId_Call{Call: _e.mock.On("GetUserId", token)}
}

func (_c *MockTokenService_GetUserId_Call) Run(run func(token string)) *MockTokenService_GetUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GetUserId_Call) Return(uUID uuid.UUID, err error) *MockTokenService_GetUserId_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockTokenService_GetUserId_Call) RunAndReturn(run func(token string) (uuid.UUID, error)) *MockTokenService_GetUserId_Call {
	_c.Call.Return(run)
	return _c
}

// IsValid provides a mock function for the type MockTokenService
func (_mock *MockTokenService) IsValid(token string) bool {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTokenService_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type MockTokenService_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) IsValid(token interface{}) *MockTokenService_IsValid_Call {
	return &MockTokenService_IsValid_Call{Call: _e.mock.On("IsValid", token)}
}

func (_c *MockTokenService_IsValid_Call) Run(run func(token string)) *MockTokenService_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_IsValid_Call) Return(b bool) *MockTokenService_IsValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTokenService_IsValid_Call) RunAndReturn(run func(token string) bool) *MockTokenService_IsValid_Call {
	_c.Call.Return(run)
	return _c
}
